# Generated by Django 2.2.3 on 2019-07-28 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('owner', models.EmailField(default='', max_length=50, validators=[django.core.validators.EmailValidator('Not an email')])),
            ],
            options={
                'ordering': ('owner', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hands_count', models.IntegerField(default=0)),
                ('max_hands', models.IntegerField(default=3)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Planet')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator('Not an email')])),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Incorrect age!')])),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Planet')),
            ],
        ),
    ]
